//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Begin @ {2} ({3} UTC){1}.
        /// </summary>
        internal static string CONSOLE_APP_BOJ {
            get {
                return ResourceManager.GetString("CONSOLE_APP_BOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Begin @ {2}{1}.
        /// </summary>
        internal static string CONSOLE_APP_BOJ_NO_UTC {
            get {
                return ResourceManager.GetString("CONSOLE_APP_BOJ_NO_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} End - {2} ({3} UTC){0}Elapsed time: {4}.
        /// </summary>
        internal static string CONSOLE_APP_EOJ {
            get {
                return ResourceManager.GetString("CONSOLE_APP_EOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} End - {2}{0}Elapsed time: {3}.
        /// </summary>
        internal static string CONSOLE_APP_EOJ_NO_UTC {
            get {
                return ResourceManager.GetString("CONSOLE_APP_EOJ_NO_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  End{0}.
        /// </summary>
        internal static string CONSOLE_APP_EOJ_REPLACEMENT_TOKEN {
            get {
                return ResourceManager.GetString("CONSOLE_APP_EOJ_REPLACEMENT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  End - .
        /// </summary>
        internal static string CONSOLE_APP_EOJ_SPLIT_TOKEN {
            get {
                return ResourceManager.GetString("CONSOLE_APP_EOJ_SPLIT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    Exit code = {0}{1}{1}.
        /// </summary>
        internal static string CONSOLE_APP_EXIT_CODE {
            get {
                return ResourceManager.GetString("CONSOLE_APP_EXIT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:An {1} exception occurred in routine {2}.{8}                         Message            = {3}{8}                         Console.CursorLeft = {4}{8}                         Console.CursorTop  = {5}{8}                         _intInitialCol     = {6}{8}                         _intInitialRow     = {7}.
        /// </summary>
        internal static string ERRMSG_EXCEPTION_BARE_BONES {
            get {
                return ResourceManager.GetString("ERRMSG_EXCEPTION_BARE_BONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Unknown status code, {0}.
        /// </summary>
        internal static string ERRMSG_UNKNOWN_EXIT_CODE {
            get {
                return ResourceManager.GetString("ERRMSG_UNKNOWN_EXIT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press the ENTER (Return) key to exit the program..
        /// </summary>
        internal static string MSG_CARBON_UNIT_DEFAULT {
            get {
                return ResourceManager.GetString("MSG_CARBON_UNIT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to stop the countdown..
        /// </summary>
        internal static string MSG_INTERRUPTCRITERION_ANYKEY {
            get {
                return ResourceManager.GetString("MSG_INTERRUPTCRITERION_ANYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the ENTER key to stop the countdown..
        /// </summary>
        internal static string MSG_INTERRUPTCRITERION_CARRIAGERETURN {
            get {
                return ResourceManager.GetString("MSG_INTERRUPTCRITERION_CARRIAGERETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The countdown cannot be stopped..
        /// </summary>
        internal static string MSG_INTERRUPTCRITERION_NONE {
            get {
                return ResourceManager.GetString("MSG_INTERRUPTCRITERION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}INTERNAL ERROR in routine WizardWrx.ConsoleAppAids3.ConsoleAppStateManager.NormalExit:{2}    Value given as argument penmNormalExitAction  = {0}{2}    Override substituted for above argument value = {1}{2}.
        /// </summary>
        internal static string NORMAL_EXIT_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("NORMAL_EXIT_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1} seconds..
        /// </summary>
        internal static string TIMEDWAIT_COUNTDOWN_MSG_TPL {
            get {
                return ResourceManager.GetString("TIMEDWAIT_COUNTDOWN_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program ending.
        /// </summary>
        internal static string TIMEDWAIT_COUNTDOWN_WAITING_FOR {
            get {
                return ResourceManager.GetString("TIMEDWAIT_COUNTDOWN_WAITING_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} NOW, after pausing for {1} of {2} programmed seconds..
        /// </summary>
        internal static string TIMEDWAIT_DONE_EARLY_MSG_TPL {
            get {
                return ResourceManager.GetString("TIMEDWAIT_DONE_EARLY_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} NOW..
        /// </summary>
        internal static string TIMEDWAIT_DONE_MSG_TPL {
            get {
                return ResourceManager.GetString("TIMEDWAIT_DONE_MSG_TPL", resourceCulture);
            }
        }
    }
}
